# NumPy for Machine Learning & Deep Learning
## Course Instructor - Gagan P, PESU-IO Slot 20

### This workbook contains all the essential codes using NumPy Library

NumPy is the **foundation of numerical computing** in Python.  
It powers **tensors**, **matrix operations**, and **vectorized math** used in ML/DL.


## 1. Importing NumPy & Creating Arrays
NumPy arrays (`ndarray`) are like Python lists but faster and more efficient for numerical operations.

Ways to create arrays:
- From Python lists
- Using built-in functions (`arange`, `linspace`, `zeros`, `ones`, `eye`, `random`)


In [1]:
import numpy as np

# From Python list
arr = np.array([1, 2, 3, 4])            # Converts python list to NumPy array
print("Array from list:", arr)

# Range of numbers
print("Arange 0-9:", np.arange(10))      # like Python range, but returns array

# Matrices(Multi-Dimensional Arrays) in NumPy
matrix=np.array([[1,2,3], [4,5,6], [7,8, 9]])          # each element is a row, it has 3 arrays and each array has 3 elements, so the shape is (3,3)
                                                       #shape is the size of the matrix in the form (m, n)  (m rows, n columns)
print(matrix)

print("Matrix: ", np.random.rand(3,2))      # .random.rand generates a random number,
                                            # (3,3) is the shape of the matrix, with m rows(here 3) and n columns( here 2)




# Zeros/Ones/Identity
print("Zeros:", np.zeros((2, 3)))        # 2x3 matrix of zeros
print("Ones:", np.ones((3, 3)))          # 3x3 matrix of ones
print("Identity:", np.eye(3))            # 3x3 identity matrix

# Random numbers
print("Random [0,1):", np.random.rand(2, 3))     # uniform distribution and the numbers lie from 0 to 1
print("Random normal:", np.random.randn(2, 3))   # normal distribution, the numbers have mean=0 and variance=1
print("Random integers:", np.random.randint(1, 10, (2, 3)))  # random ints 1: Lower bound (inclusive),  10: Upper bound (exclusive), (2, 3): Shape as a tuple


Array from list: [1 2 3 4]
Arange 0-9: [0 1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix:  [[0.07938249 0.89223074]
 [0.75686294 0.28651774]
 [0.62585329 0.04875313]]
Zeros: [[0. 0. 0.]
 [0. 0. 0.]]
Ones: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Identity: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Random [0,1): [[0.53764441 0.75171472 0.63483626]
 [0.23892779 0.01970514 0.83816223]]
Random normal: [[-0.97963644  0.57404085 -0.37954795]
 [-0.44880274  1.15410655  0.42053268]]
Random integers: [[8 6 3]
 [9 2 8]]


Notice How each time .random generates different numbers

### To keep the random numbers constant everytime, we use `np.random.seed`

In [6]:
np.random.seed(42)

matrix=np.random.rand(3,3)
matrix
# Notice how it generates the same set of random numbers


array([[0.38246199, 0.98323089, 0.46676289],
       [0.85994041, 0.68030754, 0.45049925],
       [0.01326496, 0.94220176, 0.56328822]])

## 2. Array Attributes
Every NumPy array has properties to inspect:
- `shape`: dimensions (rows, columns)
- `ndim`: number of dimensions
- `size`: total number of elements
- `dtype`: data type


In [3]:
a = np.random.randint(0, 10, (3, 4))
print("Array:\n", a)
print("Shape:", a.shape)   # rows x columns
print("Dimensions:", a.ndim)
print("Total elements:", a.size)
print("Data type:", a.dtype)


Array:
 [[7 2 5 4]
 [1 7 5 1]
 [4 0 9 5]]
Shape: (3, 4)
Dimensions: 2
Total elements: 12
Data type: int64


## 3. Indexing & Slicing
Similar to Python lists but more powerful:
- Single element: `arr[row, col]`
- Slicing rows/cols
- Boolean indexing
- Fancy indexing


In [4]:
arr = np.arange(1, 13).reshape(3, 4)
print("Array:\n", arr)

# Single element
print("Element at row1,col2:", arr[0, 1])

# Row slice
print("First row:", arr[0, :])

# Column slice
print("First column:", arr[:, 0])

# Sub-matrix
print("Rows 1-2, Cols 2-3:\n", arr[0:2, 1:3])

# Boolean indexing
print("Elements > 5:", arr[arr > 5])

# Fancy indexing (pick specific rows/cols)
print("Rows 0 & 2:\n", arr[[0, 2]])

print("Columns 0 and 2\n", arr[:, [0,2]])


Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Element at row1,col2: 2
First row: [1 2 3 4]
First column: [1 5 9]
Rows 1-2, Cols 2-3:
 [[2 3]
 [6 7]]
Elements > 5: [ 6  7  8  9 10 11 12]
Rows 0 & 2:
 [[ 1  2  3  4]
 [ 9 10 11 12]]
Columns 0 and 2
 [[ 1  3]
 [ 5  7]
 [ 9 11]]


## 4. Elementwise Operations
NumPy allows vectorized math without loops.
This is critical for ML (matrix operations, gradients, etc.).


In [ ]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

# Elementwise math
print("Addition:", x + y)
print("Multiplication:", x * y)
print("Power:", x ** 2)

# Universal functions (ufuncs)
print("Sqrt:", np.sqrt(x))
print("Exp:", np.exp(x))
print("Log:", np.log(x))


## 6. Reshaping
Reshaping is common when preparing input for ML models.
- `reshape`: change shape without changing data
- `ravel`/`flatten`: 1D view of array
- `transpose` / `T`: swap rows/columns


In [ ]:
matrix=np.arange(12)
print(matrix)
print("after reshaping:\n")
matrix_new=np.reshape(matrix,  (3,4))      # here the the total elements should match or else you will get error
print(matrix_new)

matrix_new=matrix_new.T   # arr.T transposes the matrix, rows become column and vice-versa (m,n)->(n, m)
print(matrix_new)

print(matrix_new.flatten())      #flatten the matrix

## 8. Aggregations
Used for computing dataset statistics (mean, variance, etc.).


In [ ]:
data = np.random.randint(1, 100, (5, 4))
print("Data:\n", data)
print("Mean:", data.mean())
print("Std deviation:", data.std())
print("Min:", data.min())
print("Max:", data.max())
print("Column-wise mean:", data.mean(axis=0))
print("Row-wise sum:", data.sum(axis=1))


## 9. Linear Algebra
NumPy powers matrix math needed for ML/DL:
- Dot product
- Matrix multiplication
- Inverse & determinant
- Eigenvalues/vectors


In [ ]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

print(arr1+arr2)                 #adds each element from same position from each array
print(np.dot(arr1, arr2))        # here it will be 1*4 + 2*5 + 3*6



A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 0], [1, 2]])

print("Dot product:", np.dot(A, B))       # matrix multiplication
print("Matrix product (@):", A @ B)       #another method for matrix multiplication

# Inverse & determinant
print("Determinant:", np.linalg.det(A))
print("Inverse:\n", np.linalg.inv(A))




# Practice Zone
Try these small tasks:
1. Create a 5x5 array with values 0–24 and extract the center 3x3 submatrix.
2. Generate 100 random numbers and compute their mean and std deviation.
3. Create a 3x3 identity matrix and multiply it with a random 3x3 matrix.
4. Reshape a 1D array of 16 numbers into a 4x4 matrix and compute row-wise sums.
5. Simulate a simple dataset: create 10 samples with 3 features each using `np.random.randn`.


In [ ]:
# Your Code Here